services:
  web:
    build:
      context: .
      dockerfile: Dockerfile

    command: sleep infinity

    ports:
      - "8082:8082"
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
